name: Deploy to Kubernetes

on:
  push:
    branches:
      - main   # 배포를 수행할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2   # GitHub Actions에서 코드를 체크아웃하는 액션 사용

    - name: Install kubectl
      run: |
        VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        curl --silent --location "https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl" > /tmp/kubectl
        chmod +x /tmp/kubectl
        sudo mv /tmp/kubectl /usr/local/bin/kubectl   # kubectl 설치

    - name: Configure Kubernetes access
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}   # GitHub Secrets에 kubeconfig 파일을 등록하고 사용
      run: |
        mkdir $HOME/.kube
        echo "$KUBECONFIG" > $HOME/.kube/config   # kubeconfig 설정

    - name: Verify Kubernetes connection
      run: |
        kubectl cluster-info   # Kubernetes 클러스터에 연결되었는지 확인하는 명령 실행
